version: '3.7'
services:
  opencatd:
    image: mirrors2/opencatd-open
    container_name: opencatd-open
    restart: unless-stopped
    #network_mode: host
    ports:
      - 80:80
    volumes:
      - $PWD/db:/app/db
    logging:
      # driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    # environment:
    #   Vertex: |
    #     {
    #       "type": "service_account",
    #       "universe_domain": "googleapis.com"
    #     }

        